In [1]:
import numpy as np
import sys
import time

In [2]:
arr = np.array([1,2,3,45,6,59])

In [3]:
type(arr)
li = [i for i in range(1,10000000)]
arr1 = np.array(li)

In [4]:
sys.getsizeof(np.array([1,2,3]))
#1 - 112
#2 - 128
# 16 - 8 B
#80000104
24/3

8.0

In [5]:
sys.getsizeof([1,2,3])
#1 - 56
#2 - 72
# 16 - 8 B
#89095160
32/3

10.666666666666666

In [6]:
list1 = [i for i in range(1,10000000)]
list2 = [i for i in range(1,10000000)]
list3 = [0 for i in range(1,10000000)]
start = time.time()
for i in range(len(list1)):
    list3[i] = list1[i] + list2[i]

end = time.time()
total = end - start
total

3.6049978733062744

In [7]:
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
arr3 = arr1 + arr2

end = time.time()
total = end - start
total

0.042151689529418945

In [8]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [11]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
import random
np.random.seed(5)
arr = np.random.randint(1,10,5)

In [32]:
arr

array([4, 7, 7, 1, 9], dtype=int32)